### ISSUE TITLE
W1_Tutorial1 TypeError

### ISSUE THREAD

**Issue by camilodoa** [CIS-522/course-content#10]
In order to work properly with Exercise 4, the solution to Exercise 2 (specifically the values array) must be converted to/defined as a Tensor. If it is a numpy array, it will cause the following error:

```
Line 82: TypeError: can’t assign a numpy.ndarray to a torch.FloatTensor
```

Adding this type requirement to Exercise 2's description could avoid this issue for others.

**Comment by ssnio** [comment]
Thank you. Fixed.
Following comment was added in Week1 Part 1 Exercise 2:
IMPORTANT: Make sure to use PyTorch tensors and NOT numpy arrays!
