### ISSUE TITLE
Airtable submission breaks if users don't run all cells 

### ISSUE THREAD

**Issue by kelsonSS** [CIS-522/course-content#13]
This is course we're required to submit to airtable whether or not we complete the lesson. However, it seems the airtable submission was built with the assumption that all cells will be run.  It is not possible to remind users to "run all" cells because several cells are built to fail if the user does not comment the relevant lines out

## Proposed Solution

pre-allocate all fields that will be sent to Airtable with NAs. that way if a user finishes early and doesn't run all cells, they will still be able to submit easily.

**Comment by jordanlei** [comment]
Resolved with #20 
What changed: we added try/catch statements that will automatically populate the airtable before submission, even for missing fields. The airtable cells are now "atomic" in the sense that they can run independently of any of the other cells in the notebook.
