### ISSUE TITLE
Need to show/interact with board tensor

### ISSUE THREAD

**Issue by kelsonSS** [CIS-522/course-content#16]
Many people in my pod were confused because they couldn't visualize / play with the the representation of the boards. because of this it was too much of a cognitive leap to get to exercise 2. 

## Proposed Solution

at  section 1.1 after first rendering the board, add a new section showing the underlying boards tensor and have them solve a problem that involves manipulation of the boards tensor. (i.e how many pieces does black have in the first game? or how many pieces are on each row). That way the students will understand how to play with the 3d tensor and solution to problem 2 will be a natural extension of what they just learned.

**Comment by kelsonSS** [comment]
[Here is a Gist with my proposed changes](https://colab.research.google.com/gist/kelsonSS/917ed3cdcb75867e24706578adaf2667/othello-intro-rework.ipynb#scrollTo=WltjDpZrj3Vk)

You'll note I try to show what's going on under the hood and have students interact with the board tensor early.
This way  exercise 2 should feel like a natural extension of what we've taught them up to this point.

**Comment by aribenjamin** [comment]
Here are my edits to the now Exercise 0:
```python
def count_pieces(game:OthelloGame, whoami):
    """A function to sum the number of pieces on the board of a given player
    current player (whoami).
    Inputs: game, an instance of OthelloGame
            whoami (int) 1 or 2, whose turn it is
    Outputs:
            populous_row: a 1d pytorch tensor of shape (n_games)"""

    #####################################################################
    # Fill in missing code (...),
    # then remove or comment the line below to test your function.
    ## hint 1: inspect game.boards
    ## hint 2: which dimension should you sum over to get row information?
    # IMPORTANT: Make sure to use PyTorch tensors and NOT numpy arrays!
    raise NotImplementedError("Complete the count_pieces function")
    #####################################################################

    n_my_pieces = ...

    return n_my_pieces

## Uncomment to test code
# game = OthelloGame(n_games=2) 
# for turn in range(4): # take some actions in both games
#     actions = actions_as_tensor(game.get_available_actions())
#     act = actions[[0,1],[0,2]]
#     game.step(act)

# game.render()
# print(count_pieces(game, 1))
```
Same idea as yours, but I edited the task so that it's slightly easier and so it builds towards a possible implementation of Exercise 2. I took away the part where they have to deal with the mechanics of action selection (after deleting Exercise 4, which deals with this, this won't be an issue if they don't learn it fully).

**Comment by kelsonSS** [comment]
that's fair.  you'll need to change/remove the hints as they are for a different problem
