### ISSUE TITLE
Missing # for the last line of the comment section

### ISSUE THREAD

**Issue by sherafatia** [CIS-522/course-content#18]
#####################################################################
    # Fill in missing code (...),
    # then remove or comment the line below to test your function.
    # Your heuristic doesn't need to be perfect. Just try to capture something
    # about "goodness" or "badness" of a board.
    # Remember that board_states is 3d (n_games, x, y) 
    # and we want a value for each game.
    # You may need to code multiple lines and use auxiliary variables
    # IMPORTANT: Make sure to use PyTorch tensors and NOT numpy arrays!
    raise NotImplementedError("Complete the my_board_value function")
    #####################################################################

**Comment by wrongu** [comment]
What is missing? Having `raise NotImplementedError` uncommented is intended. This means that it will raise an error unless students replace it with their own code.

**Comment by aribenjamin** [comment]
Right, this is the workflow for exercises. Once you write your exercise, you're supposed to comment this out.

**Comment by sherafatia** [comment]
Got it. It wasn't obvious to me that it was intentional! : )
