### ISSUE TITLE
Player 2 always wins in graph representations

### ISSUE THREAD

**Issue by fededagos** [CIS-522/course-content#19]
It is not always straightforward to interpret graphs with wins/lose/draws percentages. Especially in the example where we can tweak epsilon, Player2 is the winner no matter what combination of values for epsilon is chosen, which might be confusing. The same problem is present also in graphs of the same type in later sessions. Maybe add a clearer legend?

**Comment by wrongu** [comment]
This is not the usual result. What value function did you use? When `epsilon --> 0` it means the games are deterministic, so even though 100 games are played, it is essentially running the same sequence of moves 100 times, so whoever wins one game will win all games. We had intended that this issue of deterministic games would come up naturally as part of the "play around with epsilon" exercise. Perhaps we should rephrase the prompt a bit better? (We can say something like "Notice that one player wins 100% of the games when epsilon is 0. Why is this?" as an explicit prompt?)

**Comment by fededagos** [comment]
I am attaching some sample images to explain better what I mean. Notice in particular how though the values for epsilon are reversed for player 1 and player 2 in the second and fifth example, player 2 is still winning. I used the value function provided in the solution for the heuristic agent. Maybe it is me misinterpreting the graphs somehow, then it will be nice to add some more explanation on how to not be misinterpreting it.
It would be still nice to add a prompt explicitly asking what happens when epsilon = 0 
Example 1:
<img width="558" alt="ex1" src="https://user-images.githubusercontent.com/49490021/104953464-c1844580-59c6-11eb-9899-0634fba67adf.png">
Example 2:
<img width="558" alt="ex2" src="https://user-images.githubusercontent.com/49490021/104953467-c2b57280-59c6-11eb-82cf-54aeeb951d2f.png">
Example 3:
<img width="558" alt="ex3" src="https://user-images.githubusercontent.com/49490021/104953471-c34e0900-59c6-11eb-9583-9bf8145436eb.png">
Example 4:
<img width="558" alt="ex4" src="https://user-images.githubusercontent.com/49490021/104953472-c3e69f80-59c6-11eb-9635-0cfdce59946d.png">
Example 5
<img width="558" alt="ex5" src="https://user-images.githubusercontent.com/49490021/104953474-c3e69f80-59c6-11eb-896e-cab55e37e529.png">

**Comment by aribenjamin** [comment]
These graphs depict the outcomes of many different games, so P1 does win _sometimes_, but yes you're right to point out that P2 has the advantage here. It's an odd feature of Othello – but it also has something to do with one's gameplaying style, obviously. I can't say I can give you a proof or anything of why this should happen with e-greedy playing. It may not be worth discussing.

We're thinking of removing the two-column format of this plot, and only showing one column (in which who gets to play P1 is shuffled between agents). Would this resolve your confusion?

**Comment by fededagos** [comment]
Thank you for the explanation. Yes, I think removing the two-column formatting would prevent the confusion
