### ISSUE TITLE
W2 T1 Airtable broken

### ISSUE THREAD

**Issue by fededagos** [CIS-522/course-content#36]
Cell runs but no form is displayed.

**Comment by ssnio** [comment]
in our runs, both content and feedback forms show up. Could you please retry and create snapshots. Thank you.

**Comment by fededagos** [comment]
A copy of a test notebook with the issue present: 
https://colab.research.google.com/drive/11mvs0H_e17ib9vGafWefIgA7FBPyJ-MS?usp=sharing
It is interesting because it happens to be working on Safari and Firefox, but not on Chrome.
Even more, interestingly, it still does not work with all Chrome extensions disabled, but it does work in Firefox with several AdBlockers turned on (uBlock, Decentraleyes, Tampermonkey with Anti-Adblock killer).
Furthermore, the form directly below (feedback) has no problem.
Really have no idea what is wrong.

**Comment by ssnio** [comment]
Thank you! I think this is too complicated to address :-) but thank you for exploring. If more people raise the issue, we may need to find a workaround.
