### ISSUE TITLE
W2 T1 : Section 2.2 content misplaced

### ISSUE THREAD

**Issue by fededagos** [CIS-522/course-content#37]
The graph represented in section 2.2 is only fully explained after the video in section 3.

**Comment by spirosChv** [comment]
Indeed Section 2.2 was misplaced and given the Video 3 was redundant. Now, we have changed the position of this section, and we have implemented two additional exercises on computational graphs with a small, toy graph.

Thank you for pointing this out. The updated tutorial will be merged on the master-branch shortly.
