### ISSUE TITLE
W2 T1 - Typo in exercise 2

### ISSUE THREAD

**Issue by fededagos** [CIS-522/course-content#38]
Matrix a1 is incorrectly filled at the beginning of exercise 2: it does not correspond with the one displayed above.
Also, consider not filling up tensor b1: the way it is defined (`b1 = torch.tensor([[3], [5], [7]])`) leans towards the usage of torch.matmul, which first requires a transpose. An implementation using vectors and torch.dot might be more straightforward at first. Also maybe stress more the difference between those different operations.

**Comment by ssnio** [comment]
Fixed.
