### ISSUE TITLE
Exercise 4: chosen_action incorrectly indexed

### ISSUE THREAD

**Issue by kelsonSS** [CIS-522/course-content#6]
## Problem

The section in which students create the epsilon greedy function, the chosen action is indexed as below:
```
 if np.random.rand() < self.epsilon:
                # With probability epsilon, pick randomly among legal moves
                # (`actions` defined just above)
                chosen_action[g] = ...
            else:
                # With probability 1-epsilon, pick the move leading to the best
                # value for the current player (game.current_player)
                chosen_action[g] = ...
```

however, in the solution chosen_action is indexed: 
 ```
  chosen_action[g , : ]= ... 
```
This is either an error or a confusing inconsistency.

## Proposal:

change those two lines above to chosen_action[g , :] = ...

**Comment by ssnio** [comment]
FIXED. Thank you for your quick check and feedback. Although both notations are similar in Python for this scenario, you are correct to point out that it may have led to confusion.
