### ISSUE TITLE
W1_Tutorial1 NotImplementedError

### ISSUE THREAD

**Issue by ssnio** [CIS-522/course-content#8]
Week1 > Tutorial 1 > Exercise 4 > first code cell > class ArtificialPlayer > def select_move:
the cell includes an unfinished method NotImplementedError.
If this is an exercise, the solution should be available in a following cell, marked "# to_remove solution".

**Comment by wrongu** [comment]
This is intended. `ArtificialPlayer` is an abstract base class that is later sub-classed by the `EpsilonGreedyPlayer`. We added `select_move` here to introduce its signature and to introduce the components of a `Player` object in one place.
