### ISSUE TITLE
W1_Tutorial2 NotImplementedError

### ISSUE THREAD

**Issue by ssnio** [CIS-522/course-content#9]
Week1 > Tutorial 2 > cell: Recreate epsilon-greedy player and hand-coded value function > class ArtificialPlayer:
the class seems to be copied from tutorial 1 (also incomplete) and includes NotImplementedError.

Week1 > Tutorial 2 > Exercise 1 > first code cell > class PolicyAgentBase > def get_policy:
the cell includes an unfinished method NotImplementedError.
If this is an exercise, the solution should be available in a following cell, marked "# to_remove solution".

**Comment by wrongu** [comment]
See #8 - these `NotImplementedError`s indicate that the function will be overridden by a sub-class, not that they are exercises.
